# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/micha/Documents/UCT/HPES/YODA/memory/memory.srcs/sources_1/ip/memory_a/memory_a.xci
# IP: The module: 'memory_a' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/micha/Documents/UCT/HPES/YODA/memory/memory.srcs/sources_1/ip/memory_a/memory_a_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memory_a'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/micha/Documents/UCT/HPES/YODA/memory/memory.srcs/sources_1/ip/memory_a/memory_a.xci
# IP: The module: 'memory_a' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/micha/Documents/UCT/HPES/YODA/memory/memory.srcs/sources_1/ip/memory_a/memory_a_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memory_a'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
