# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/micha/Documents/UCT/HPES/YODA/memory/memory.srcs/sources_1/ip/memory_b/memory_b.xci
# IP: The module: 'memory_b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/micha/Documents/UCT/HPES/YODA/memory/memory.srcs/sources_1/ip/memory_b/memory_b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memory_b'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/micha/Documents/UCT/HPES/YODA/memory/memory.srcs/sources_1/ip/memory_b/memory_b.xci
# IP: The module: 'memory_b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/micha/Documents/UCT/HPES/YODA/memory/memory.srcs/sources_1/ip/memory_b/memory_b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memory_b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
